---
name: docs-publish
on: 
  push:
      branches:
          - main
  workflow_dispatch:
jobs:
  mkdoc-publish:
    name: Build andDeploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs/mkdocs.yml
          EXTRA_PACKAGES: graphviz plantuml texlive-full pandoc ghostscript
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt