---
# TO BE USED ONLY FOR GHA that downloads plantuml.jar into the working directory.


# Backstage Docs: https://backstage.io/docs/features/techdocs/creating-and-publishing#enable-documentation-for-an-already-existing-entity
# https://www.mkdocs.org/user-guide/configuration/#site_name

site_name: 'Salduba Documentation'
site_description: Documentation using mkdocs
repo_url: 'https://github.com/jmpicnic/documents'
repo_name: 'GitHub'

# https://www.mkdocs.org/user-guide/configuration/#docs_dir
docs_dir: 'root-docs'

# See: https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin
extra:
  status:
    new: Recently created, author still needs to provide structure
    draft: Actively being worked by the author, open for contributions
    review: Under peer review.
    published: Ready for general use
    updating: Currently being updated. Should provide link to previous version.
    deprecated: Old, kept for reference but should not be used anymore.

# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
nav:
  - Home: index.md
#  - Index: index.md
#  - Salduba:
#      - Clients:
#          - AEA:
#              - Current:
#                  - SCIO:
#                      - Sw Capabilities Questionnaire: salduba/clients/aea/current/scio/software-capabilities-questionnaire.md

# See https://squidfunk.github.io/mkdocs-material/reference/code-blocks/package
theme:
  name: material
  #  static_templates: "techdocs_metadata.json"
  features:
    - content:
        code.annotate
        tooltips
    - navigation
        instant
        tracking
        path

# ```yaml
# some:
#   code: "asdf" # (1)
# ```
# 1. :man_raising_hand: I'm a code annotation!!

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - tables
  - def_list
  - admonition
  - toc
#  - markdown_inline_graphviz
  - plantuml_markdown:
      base_dir: 'domain:merchandising:sales-transaction'
      # plantuml_cmd: 'java -Djava.awt.headless=true -Dplantuml.include.path="domain:merchandising:sales-transaction" -jar plantuml.jar'
      #  backstage seems to block svg, so set to png for Backstage
      format: png
  # https://pypi.org/project/mdx-truly-sane-lists/
  - mdx_truly_sane_lists
  # https://github.com/crisluengo/mdx_math_svg
#  - mdx_math_svg:
#      inline_class: math
#      display_class: math
  # See https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - monorepo
  - search
  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages
  # https://github.com/shyamd/mkdocs-bibtex
  - bibtex:
      bib_dir: "root-docs/bib"
      bib_by_default: true
      csl_file: "root-docs/bib/ieee-spectrum.csl"
      cite_inline: false
